export const Items = [
	{ name: "1", id: 1, key: "a" },
	{ name: "1", id: 1, key: "b" },
	{ name: "2", id: 2, key: "c" },
	{ name: "2", id: 2, key: "d" },
	{ name: "3", id: 3, key: "e" },
	{ name: "3", id: 3, key: "f" },
	{ name: "4", id: 4, key: "g" },
	{ name: "4", id: 4, key: "h" },
	{ name: "5", id: 5, key: "i" },
	{ name: "5", id: 5, key: "j" },
	{ name: "6", id: 6, key: "k" },
	{ name: "6", id: 6, key: "l" },
	{ name: "7", id: 7, key: "m" },
	{ name: "7", id: 7, key: "n" },
	{ name: "8", id: 8, key: "o" },
	{ name: "8", id: 8, key: "p" },
];
